### ISSUE TITLE
add DogPlugin into bot_plugins

### ISSUE THREAD

**Issue by MShel** [MShel/PyChatBot#25]
It would be cool to be able to get info about dog breeds right from your chat.

Take a look at https://dog.ceo/dog-api/
and here is the implementation of other plugin which should direct you the right way.
https://github.com/MShel/PyChatBot/blob/master/bot_plugins/Recipe.py

To see it working add plugin to plugin dictionary (https://github.com/MShel/PyChatBot/blob/master/PluginDict.py)

**Comment by ewenchou** [comment]
I can look into this

**Comment by MShel** [comment]
awesome sauce!

**Comment by ewenchou** [comment]
Please take a look at pull request #26 thanks!

**Comment by MShel** [comment]
looks good
